version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "k1-topic:1:1"
      KAFKA_CREATE_TOPICS: "k2-topic:1:1"
    # restart: always

  
  cassandradb:
    image: cassandra
    container_name: cassandradb
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_HOST=cassandradb
      - CASSANDRA_RPC_ADDRESS=0.0.0.0

  # cassandra:
  #   container_name: cassandra
  #   image: cassandra:3.9
  #   # volumes:
  #   #     - /path/of/host/for/cassandra/:/var/lib/cassandra/
  #   ports:
  #       - 7000:7000
  #       - 7001:7001
  #       - 7199:7199
  #       - 9042:9042
  #       - 9160:9160
  #   environment:
  #       - CASSANDRA_CLUSTER_NAME='cassandra-cluster'
  #       - CASSANDRA_NUM_TOKENS=256
  #       - CASSANDRA_RPC_ADDRESS=0.0.0.0
  #   restart: always


#   cassandra:
#     image: docker.io/bitnami/cassandra:latest
#     ports:
#       - '7000:7000'
#       - '9042:9042'
#     environment:
#       - CASSANDRA_SEEDS=cassandra
#       # - CASSANDRA_PASSWORD_SEEDER=yes
#       - CASSANDRA_HOST=cassandradb
# #      - CASSANDRA_USERNAME=user
# #      - CASSANDRA_PASSWORD=pass123
#       # - CASSANDRA_CFG_RACKDC_PREFER_LOCAL=true

  m1application:
    ports:
      - "8880:8880"
    build:
      context: M1
      args:
        JAR_FILE: /M1/target/M1Application.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    container_name: m1application
    depends_on:
      - kafka

  
  m2application:
    ports:
      - "8881:8881"
    build:
      context: M2
      args:
        JAR_FILE: /M2/target/M2Application.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    container_name: m2application
    depends_on:
      - kafka

  m3application:
    ports:
      - "8882:8882"
    build:
      context: M3
      args:
        JAR_FILE: /M3/target/M3Application.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    container_name: m3application
    depends_on:
      - kafka
      - cassandradb
    restart: always
  
  m4application:
    ports:
      - "8883:8883"
    build:
      context: M4
      args:
        JAR_FILE: /M4/target/MApplication.jar
    container_name: m4application
    depends_on:
      - cassandradb
    restart: always

  webapplication:
    image: webapplication
    build: web
    container_name: webapplication
    # restart: always
    ports:
      - "8080:80"
